 #pragma once
#include "MASTER.h"
#include "GLOBAL.h"
#include "ThirdPartyHeadersBegin.h"
#include <boost/make_shared.hpp>
#include <boost/shared_ptr.hpp>
#include <vector>
#include "ThirdPartyHeadersEnd.h"
#include "fileio.h"
struct AuxData_s { typedef boost::shared_ptr<AuxData_s> Ptr; struct AuxDataItem { AuxDataItem(AuxDataType_e auxDataType, ___372 ___3362, std::string const& ___2686, std::string const& value) : m_auxDataType(auxDataType) , m_retain(___3362) , ___2496(___2686) , ___2668(value) {} AuxDataType_e m_auxDataType; ___372 m_retain; std::string ___2496; std::string ___2668; AuxDataItem() {} void writeToFile(tecplot::___3934::FileWriterInterface& outputFile, bool ___4480) const { tecplot::tecioszl::writeScalar(outputFile, (uint32_t)m_auxDataType, ___4480); tecplot::tecioszl::writeScalar(outputFile, m_retain, ___4480); tecplot::tecioszl::___4544(outputFile, ___2496, ___4480); tecplot::tecioszl::___4544(outputFile, ___2668, ___4480); } uint64_t sizeInFile(bool ___4480) const { return tecplot::tecioszl::scalarSizeInFile((uint32_t)m_auxDataType, ___4480) + tecplot::tecioszl::scalarSizeInFile(m_retain, ___4480) + tecplot::tecioszl::stringSizeInFile(___2496, ___4480) + tecplot::tecioszl::stringSizeInFile(___2668, ___4480); } AuxDataItem(tecplot::___3934::___1397& inputFile, bool readASCII) { READ_ENUM(m_auxDataType, AuxDataType_e, inputFile, readASCII); tecplot::tecioszl::readScalar(inputFile, m_retain, readASCII); tecplot::tecioszl::readString(inputFile, ___2496, readASCII); tecplot::tecioszl::readString(inputFile, ___2668, readASCII); } }; std::vector<AuxDataItem> m_auxDataItems; AuxData_s() {} void writeToFile(tecplot::___3934::FileWriterInterface& outputFile, bool ___4480) const { tecplot::tecioszl::writeVectorOfObjects(outputFile, m_auxDataItems, ___4480); } uint64_t sizeInFile(bool ___4480) const { return tecplot::tecioszl::vectorOfObjectsSizeInFile(m_auxDataItems, ___4480); } static Ptr makePtr(tecplot::___3934::___1397& inputFile, bool readASCII) { Ptr ___3359 = boost::make_shared<AuxData_s>(); tecplot::tecioszl::readVectorOfObjects(inputFile, ___3359->m_auxDataItems, readASCII); return ___3359; } };
