 #pragma once
#include "ThirdPartyHeadersBegin.h"
#include <limits>
#include <vector>
#include <boost/make_shared.hpp>
#include <boost/shared_ptr.hpp>
#include "ThirdPartyHeadersEnd.h"
#include "MASTER.h"
#include "GLOBAL.h"
#include "CodeContract.h"
#include "fileio.h"
namespace tecplot { namespace tecioszl { struct ___1360 { static double const GHOST_VALUE; typedef boost::shared_ptr<___1360> Ptr; FieldDataType_e ___2460; size_t ___2669; ValueLocation_e ___2670; ___1360(); virtual ~___1360(); virtual void ___3505(size_t index, double value) = 0; virtual double ___1779(size_t index) = 0; virtual void appendValue(double value) = 0; virtual void reserveValues(size_t count) = 0; virtual void assignValues(size_t count, double value) = 0; virtual void* getRawPointer() = 0; virtual size_t storedValueCount() = 0; void ___1758(double& minVal, double& maxVal) const; void ___3500(double minVal, double maxVal); virtual void writeToFile(tecplot::___3934::FileWriterInterface& outputFile, bool ___4480) const = 0; virtual uint64_t sizeInFile(bool ___4480) const = 0; virtual void readFromFile(tecplot::___3934::___1397& inputFile, bool readASCII) = 0; static Ptr makePtr(tecplot::___3934::___1397& inputFile, bool readASCII); protected: void updateMinMax(double value); double m_minValue; double m_maxValue; }; template <typename T> class TypedFieldData : public ___1360 { public: TypedFieldData(); void ___3505(size_t index, double value); double ___1779(size_t index); void appendValue(double value); void reserveValues(size_t count); void assignValues(size_t count, double value); void* getRawPointer(); size_t storedValueCount(); virtual void writeToFile(tecplot::___3934::FileWriterInterface& outputFile, bool ___4480) const; virtual uint64_t sizeInFile(bool ___4480) const; virtual void readFromFile(tecplot::___3934::___1397& inputFile, bool readASCII); private: std::vector<T> ___2672; }; class TypedFieldDataFactory { public: boost::shared_ptr<___1360> make(FieldDataType_e type); }; template <typename T> inline TypedFieldData<T>::TypedFieldData() { } template <typename T> inline void TypedFieldData<T>::___3505(size_t index, double value) { ___2672[index] = static_cast<T>(value); updateMinMax(value); } template <typename T> inline double TypedFieldData<T>::___1779(size_t index) { return static_cast<double>(___2672[index]); } template <typename T> inline void TypedFieldData<T>::appendValue(double value) { ___2672.push_back(static_cast<T>(value)); updateMinMax(value); } template <typename T> inline void TypedFieldData<T>::reserveValues(size_t count) { ___2672.reserve(count); } template <typename T> inline void TypedFieldData<T>::assignValues(size_t count, double value) { ___2672.assign(count, static_cast<T>(value)); updateMinMax(value); } template <typename T> inline void* TypedFieldData<T>::getRawPointer() { if (___2672.empty()) return NULL; return (reinterpret_cast<void*>(___2672.data())); } template <typename T> inline size_t TypedFieldData<T>::storedValueCount() { return ___2672.size(); } inline boost::shared_ptr<___1360> TypedFieldDataFactory::make(FieldDataType_e type) { boost::shared_ptr<___1360> ___3359; switch(type) { case FieldDataType_Float:
___3359 = boost::make_shared<TypedFieldData<float> >(); break; case FieldDataType_Double: ___3359 = boost::make_shared<TypedFieldData<double> >(); break; case FieldDataType_Int32: ___3359 = boost::make_shared<TypedFieldData<int32_t> >(); break; case FieldDataType_Int16: ___3359 = boost::make_shared<TypedFieldData<int16_t> >(); break; case FieldDataType_Byte: case ___1363: ___3359 = boost::make_shared<TypedFieldData<uint8_t> >(); break; default: ___476(___1303); ___3359 = boost::make_shared<TypedFieldData<float> >(); break; } ___3359->___2460 = type; return ___3359; } template <typename T> inline void TypedFieldData<T>::writeToFile(tecplot::___3934::FileWriterInterface& outputFile, bool ___4480) const { tecplot::tecioszl::writeScalar(outputFile, (uint32_t)___2460, ___4480); tecplot::tecioszl::writeScalar(outputFile, (uint64_t)___2669, ___4480); tecplot::tecioszl::writeScalar(outputFile, (uint32_t)___2670, ___4480); tecplot::tecioszl::writeScalar(outputFile, m_minValue, ___4480); tecplot::tecioszl::writeScalar(outputFile, m_maxValue, ___4480); tecplot::tecioszl::writeVector(outputFile, ___2672, ___4480); } template <typename T> uint64_t TypedFieldData<T>::sizeInFile(bool ___4480) const { return tecplot::tecioszl::scalarSizeInFile((uint32_t)___2460, ___4480) + tecplot::tecioszl::scalarSizeInFile((uint64_t)___2669, ___4480) + tecplot::tecioszl::scalarSizeInFile((uint32_t)___2670, ___4480) + tecplot::tecioszl::scalarSizeInFile(m_minValue, ___4480) + tecplot::tecioszl::scalarSizeInFile(m_maxValue, ___4480) + tecplot::tecioszl::vectorSizeInFile(___2672, ___4480); } template <typename T> inline void TypedFieldData<T>::readFromFile(tecplot::___3934::___1397& inputFile, bool readASCII) { tecplot::tecioszl::readScalar(inputFile, ___2669, readASCII); uint32_t tempValueLocation; tecplot::tecioszl::readScalar(inputFile, tempValueLocation, readASCII); ___2670 = static_cast<ValueLocation_e>(tempValueLocation); tecplot::tecioszl::readScalar(inputFile, m_minValue, readASCII); tecplot::tecioszl::readScalar(inputFile, m_maxValue, readASCII); tecplot::tecioszl::readVector(inputFile, ___2672, readASCII); } inline void padCCValuesIfNecessary(___1360& ___1349, ___2226 iMax, ___2226 jMax, ___2226 kMax) { ___2226 storedValueCount = checked_numeric_cast<___2226>(___1349.storedValueCount()); if (iMax > 1 && (jMax > 1 || kMax > 1) && storedValueCount % iMax == (iMax - 1)) { ___1349.appendValue(___1360::GHOST_VALUE); ++storedValueCount; } if (jMax > 1 && kMax > 1 && storedValueCount % ((int64_t)iMax * jMax) == ((int64_t)iMax * (jMax - 1))) { for (___2226 ___1840 = 0; ___1840 < iMax; ++___1840) ___1349.appendValue(___1360::GHOST_VALUE); } } }}
