#include "ThirdPartyHeadersBegin.h"
#include <boost/assign.hpp>
#include <boost/scoped_ptr.hpp>
#include <boost/unordered_map.hpp>
#include <cstdio>
#include <mpi.h>
#include <string>
#include "ThirdPartyHeadersEnd.h"
#include "MPIFileReader.h"
namespace tecplot { namespace teciompi { MPIFileReader::MPIFileReader(std::string const& ___1392, MPI_Comm comm) : m_ioStream(___1392, comm) {} MPIFileReader::~MPIFileReader() {} ___372 MPIFileReader::___2040() const { return m_ioStream.fileHandle() != NULL; } ___372 MPIFileReader::close(bool ___3362) { ___372 ___3359 = ___4227; if (___2040()) ___3359 = m_ioStream.close(___3362); ENSURE(!___2040()); ENSURE(VALID_BOOLEAN(___3359)); return ___3359; } ___3934::___1391 MPIFileReader::fileLoc() { REQUIRE(___2040()); return static_cast<___3934::___1391>(m_ioStream.fileLoc()); } ___372 MPIFileReader::___3461() { REQUIRE(___2040()); return m_ioStream.___3461(); } ___372 MPIFileReader::___3460(___3934::___1391 fileLoc) { REQUIRE(___2040()); return m_ioStream.___3460(fileLoc); } ___372 MPIFileReader::seekToFileEnd() { REQUIRE(___2040()); return m_ioStream.seekToFileEnd(); } std::string const& MPIFileReader::___1392() const { return m_ioStream.___1392(); } void MPIFileReader::___3495(___372 ___2001) { REQUIRE(VALID_BOOLEAN(___2001)); m_ioStream.___3495(___2001); } ___372 MPIFileReader::___2001() const { return m_ioStream.___2001(); } void MPIFileReader::setDataFileType(DataFileType_e ___842) { REQUIRE(VALID_ENUM(___842, DataFileType_e)); m_ioStream.setDataFileType(___842); } DataFileType_e MPIFileReader::___842() const { return m_ioStream.___842(); } ___3934::FileIOStatistics& MPIFileReader::statistics() { return m_ioStream.statistics(); } ___372 MPIFileReader::open() { REQUIRE(!___2040()); return m_ioStream.open(MPI_MODE_RDONLY); } namespace { MPI_Datatype mpiDatatypeForSize(size_t size) { static boost::unordered_map<size_t, MPI_Datatype> typeForSize = boost::assign::map_list_of<size_t, MPI_Datatype> (1, static_cast<MPI_Datatype>(MPI_CHAR)) (2, static_cast<MPI_Datatype>(MPI_SHORT)) (4, static_cast<MPI_Datatype>(MPI_INT)) (8, static_cast<MPI_Datatype>(MPI_DOUBLE)); REQUIRE(typeForSize.find(size) != typeForSize.end()); return typeForSize[size]; } } size_t MPIFileReader::fread(void* ___416, size_t size, size_t count) { REQUIRE(___2040()); int countRead = 0; MPI_Datatype ___904 = mpiDatatypeForSize(size); MPI_Status status; if (MPI_File_read(m_ioStream.fileHandle(), ___416, static_cast<int>(count), ___904, &status) == MPI_SUCCESS) MPI_Get_count(&status, ___904, &countRead); return static_cast<size_t>(countRead); } char* MPIFileReader::fgets(char* s, int size) { REQUIRE(___2040()); REQUIRE(size > 1); MPI_Status status; for (int n = 0; n < size - 1; ++n) { if (MPI_File_read(m_ioStream.fileHandle(), &s[n], 1, MPI_CHAR, &status) != MPI_SUCCESS) { s[n] = '\0'; break; } else if (s[n] == '\n') { s[n + 1] = '\0'; break; } } s[size - 1] = '\0'; return s; } int MPIFileReader::feof() { REQUIRE(___2040()); ___3934::___1391 fileLoc = m_ioStream.fileLoc(); MPI_Offset fileSize; if (MPI_File_get_size(m_ioStream.fileHandle(), &fileSize) == MPI_SUCCESS) return fileLoc < static_cast<___3934::___1391>(fileSize) ? 0 : -1;
return -1; } int MPIFileReader::getc() { unsigned char c; MPI_Status status; if (MPI_File_read(m_ioStream.fileHandle(), &c, 1, MPI_CHAR, &status) == MPI_SUCCESS) return c; return EOF; } int MPIFileReader::ungetc(int  ) { ___476(___1303); return EOF; } int MPIFileReader::fscanf(char const*  , void* /*___3252*/) { ___476(___1303); return EOF; } int MPIFileReader::fscanf(char const*  , void* /*ptr1*/, void* /*ptr2*/) { ___476(___1303); return EOF; } int MPIFileReader::fscanf(char const*  , void* /*ptr1*/, void* /*ptr2*/, void* /*ptr3*/) { ___476(___1303); return EOF; } }}
