 #pragma once
#include "ThirdPartyHeadersBegin.h"
#include <map>
#include <vector>
#include <boost/unordered_set.hpp>
#include "ThirdPartyHeadersEnd.h"
#include "SZLFEPartitionedZoneHeaderWriter.h"
#include "ZoneWriterAbstract.h"
#include "PartitionTecUtilDecorator.h"
namespace tecplot { namespace ___3934 { class ___1348; class ___1350; class ___2725; class NodeToElemMap; class ZoneInfoCache; class ItemSetIterator; class SZLFEPartitionedZoneWriter : public ___4709 { public: SZLFEPartitionedZoneWriter( uint32_t                      fileVersion, ItemSetIterator&              varIter, ___4636                   zone, ___4636                   ___341, std::vector<___372> const& ___4564, ___372                     ___4499, ___37&                   ___36, ZoneInfoCache&                zoneInfoCache); virtual ~SZLFEPartitionedZoneWriter(); protected: struct NeighborCellSubzoneInfo { std::vector<___2719> m_nodes; std::vector<___2719> m_neighborNodes; std::vector<SubzoneAddressUnorderedSet> m_cellSubzones; std::vector<std::vector<___2480> > m_varMinMaxes; }; typedef std::map<ItemAddress64::___2981, NeighborCellSubzoneInfo> NeighborCellSubzoneInfoMap; void gatherNeighborCellSubzoneInfo(NeighborCellSubzoneInfoMap& neighborCellSubzoneInfoMap, ItemAddress64::___2981 ___2978, ___4352 ___2844, ___2725& ___2724, std::vector<___1350> const& fieldDatas, ___1348 const& zoneInfo); virtual uint64_t zoneConnectivityFileSize(bool ___2001); virtual uint64_t zoneDataFileSize(bool ___2001); virtual uint64_t zoneHeaderFileSize(bool ___2001); virtual ___372 writeZoneConnectivity(FileWriterInterface& szpltFile); virtual ___372 writeZoneData(FileWriterInterface& szpltFile); virtual ___372 writeZoneHeader(FileWriterInterface& szpltFile); SZLFEPartitionedZoneHeaderWriter m_headerWriter; ZoneInfoCache& ___2681; PartitionTecUtilDecorator m_partitionTecUtil; ___2241<int32_t> m_partitionFileNums; UInt64Array m_partitionHeaderFilePositions; ___2241<Int64Array> m_secPtnNumCells; Int64Array m_partitionNumNodes; VarZoneMinMaxArray m_varPartitionMinMaxes; std::map<___4636, boost::shared_ptr<___4709> > m_partitionWriters; private: void exchangeGhostInfo(std::vector<boost::shared_ptr<___1348> >& partitionInfos); void createPartitionWriters(); }; }}
