 #pragma once
#include "ThirdPartyHeadersBegin.h"
#include <map>
#include <vector>
#include <boost/unordered_set.hpp>
#include "ThirdPartyHeadersEnd.h"
#include "SZLOrderedPartitionedZoneHeaderWriter.h"
#include "IJKPartitionTree.h"
#include "IJKZoneInfo.h"
#include "PartitionTecUtilDecorator.h"
#include "ZoneWriterAbstract.h"
namespace tecplot { namespace ___3934 { class ___1350; class ZoneInfoCache; class ItemSetIterator; class SZLOrderedPartitionedZoneWriter : public ___4709 { public: SZLOrderedPartitionedZoneWriter( uint32_t                      fileVersion, ItemSetIterator&              varIter, ___4636                   zone, ___4636                   ___341, std::vector<___372> const& ___4564, ___372                     ___4499, ___37&                   ___36, ZoneInfoCache&                zoneInfoCache); virtual ~SZLOrderedPartitionedZoneWriter(); protected: typedef std::map<ItemAddress64::SubzoneOffset_t, std::vector<___2480> > SubzoneMinMaxMap; void applyCellMinMaxesToNeighborNodeSubzones( ItemAddress64::___2981 ___2978, std::vector<___1350> const& fieldDatas, std::vector<boost::shared_ptr<___1880> >& partitionInfos, ___1862 const& partitionTree); void getPartitionExtentsWithGhostNodes( ItemAddress64::___2981 ___2978, ___1843 &partitionMinIJK, ___1843 &partitionMaxIJK); void trimGhostNodes(___1843 &partitionMaxIJK); void getPartitionExtentsWithoutGhostNodes( ItemAddress64::___2981 ___2978, ___1843 &partitionMinIJK, ___1843 &partitionMaxIJK); void retrieveNodalFieldDataPtrsForPartition( ___37& partitionTecUtilDecorator, ItemAddress64::___2981 ___2978, std::vector<___1350> &nodalFieldDatas); void throwIfBadIntersectionRange( ___1854 const& intersectionRange, ItemAddress64::___2981 ___2978, ItemAddress64::___2981 neighborPartition); void getCellMinMaxes( std::vector<___2480>& cellMinMaxes, ___2226 ___460, ___1843 const& dimensions, std::vector<___1350> const& fieldDatas); virtual uint64_t zoneConnectivityFileSize(bool ___2001); virtual uint64_t zoneDataFileSize(bool ___2001); virtual uint64_t zoneHeaderFileSize(bool ___2001); virtual ___372 writeZoneConnectivity(FileWriterInterface& szpltFile); virtual ___372 writeZoneData(FileWriterInterface& szpltFile); virtual ___372 writeZoneHeader(FileWriterInterface& szpltFile); SZLOrderedPartitionedZoneHeaderWriter m_headerWriter; ZoneInfoCache& ___2681; PartitionTecUtilDecorator m_partitionTecUtil; ___2241<int32_t> m_partitionFileNums; UInt64Array m_partitionHeaderFilePositions; UInt64Array m_partitionMinNodeNumbers; UInt64Array m_partitionMaxNodeNumbers; VarZoneMinMaxArray m_varPartitionMinMaxes; std::map<___4636, boost::shared_ptr<___4709> > m_partitionWriters; private: void exchangeGhostInfo( std::vector<boost::shared_ptr<___1880> >& partitionInfos, std::vector<___1863> const& ___2982); void applyCellMinMaxesToNeighborsInRange( std::vector<___1863> const& neighborItems, ItemAddress64::___2981 ___2978, ___1854 const& partitionRange, ___1843 const& partitionOffsetIJK, ___1843 const& partitionDimensionsIJK, std::vector<___1350> const& fieldDatas, std::vector<boost::shared_ptr<___1880> >& partitionInfos); void createPartitionWriters();
}; }}
