#include "ZoneHeaderWriterAbstract.h"
#include "ThirdPartyHeadersBegin.h"
#include <boost/assign.hpp>
#include "ThirdPartyHeadersEnd.h"
#include "AltTecUtil.h"
#include "FileWriterInterface.h"
#include "ItemSetIterator.h"
#include "SzlFileLoader.h"
#include "writeValueArray.h"
namespace tecplot { namespace ___3934 { ZoneHeaderWriterAbstract::ZoneHeaderWriterAbstract( uint32_t           fileVersion, ItemSetIterator&   varIter, ___4636        zone, ___4636        ___341, ___37&        ___36, std::string const& zoneMarkerLabel  , uint32_t           zoneMarker  , std::string const& zoneNumberLabel  , std::string const& zoneNumberSuffix  ) : m_fileVersion(fileVersion) , m_varIter(varIter) , ___2678(zone) , m_baseZone(___341) , ___2338(___36) , m_zoneMarkerLabel(zoneMarkerLabel) , m_zoneMarker(zoneMarker) , m_zoneNumberLabel(zoneNumberLabel) , m_zoneNumberSuffix(zoneNumberSuffix) {} ZoneHeaderWriterAbstract::~ZoneHeaderWriterAbstract() {} void ZoneHeaderWriterAbstract::setMarkerAndLabels( std::string const& zoneMarkerLabel, uint32_t zoneMarker, std::string const& zoneNumberLabel, std::string const& zoneNumberSuffix) { m_zoneMarkerLabel = zoneMarkerLabel; m_zoneMarker = zoneMarker; m_zoneNumberLabel = zoneNumberLabel; m_zoneNumberSuffix = zoneNumberSuffix; } ___372 ZoneHeaderWriterAbstract::___4565(FileWriterInterface& file, ___3946 const& ___3945) const { REQUIRE(file.___2040()); ___372 ___2038 = ___4227; if (file.___2001()) { ___2038 = writeValue<uint32_t, false, 0>(file, m_zoneMarkerLabel.c_str(), m_zoneMarker) && writeValue<uint32_t, false, 0>(file, m_zoneNumberLabel.c_str(), (___2678 - m_baseZone) + 1); } UInt16Array tagArray; ___2038 = ___2038 && tagArray.alloc(___3945.size()); if (___2038) { size_t numTags = 0; for (___3946::const_iterator value = ___3945.begin(); value != ___3945.end(); ++value) tagArray[numTags++] = value->first; ___2038 = ___2038 && writeValue<uint16_t, false, 0>(file, ___2840, static_cast<uint16_t>(___3945.size())) && ___4563<uint16_t, false, 0>(file, ___3944, ___2746, numTags, tagArray.data()); } if (___2038) { ___3943 tagDescriptionMap = ___4689; for (___3946::const_iterator value = ___3945.begin(); value != ___3945.end(); ++value) ___2038 = ___2038 && writeValue<uint64_t, true, 0>(file, tagDescriptionMap[value->first].c_str(), value->second); } ENSURE(VALID_BOOLEAN(___2038)); return ___2038; } uint64_t ZoneHeaderWriterAbstract::zoneHeaderTagsSizeInFile(uint16_t numTags, bool ___2001) const { uint64_t ___3359 = 0; if (___2001) ___3359 += 2 * valueSizeInFile<uint32_t, false>(___2001); ___3359 += valueSizeInFile<uint16_t, false>(___2001); ___3359 += arraySizeInFile<uint16_t, false>(static_cast<size_t>(numTags), ___2001); ___3359 += numTags * valueSizeInFile<uint64_t, true  >(___2001); return ___3359; } std::string ZoneHeaderWriterAbstract::appendZoneSuffix(std::string const& str) const { return str + m_zoneNumberSuffix; } }}
